---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudflared
  namespace: longhorn-system
automountServiceAccountToken: false

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: longhorn-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      serviceAccountName: cloudflared
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            - --no-autoupdate
            - run
            - --token-file=/etc/cloudflared/token
          volumeMounts:
            - name: tokenfile
              mountPath: /etc/cloudflared
              readOnly: true
      volumes:
        - name: tokenfile
          secret:
            secretName: longhorn-cloudflared-token
            items:
              - key: TOKEN
                path: token

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: longhorn-auth
  namespace: longhorn-system
spec:
  basicAuth:
    secret: longhorn-auth-secret

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: longhorn-system-longhorn-auth@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: longhorn.nathanwhyte.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: longhorn-frontend
                port:
                  number: 80
