apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llama
resources:
  - configmap.yaml
  - memory-service-code-configmap.yaml
  - qdrant-service.yaml
  - qdrant-statefulset.yaml
  - embedder-cpu-service.yaml
  - embedder-cpu-deployment.yaml
  - memory-service-service.yaml
  - memory-service-deployment.yaml
