---
apiVersion: v1
kind: Service
metadata:
  name: memory-service
  namespace: llama
spec:
  type: ClusterIP
  selector:
    app: memory-service
  ports:
    - name: http
      port: 80
      targetPort: 8081
      protocol: TCP
