#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

# shellcheck disable=SC2034  # the full palette is provided for stage authors; RED is unused by the library itself
if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold)
  DIM=$(tput dim)
  RESET=$(tput sgr0)
  BLUE=$(tput setaf 4)
  GREEN=$(tput setaf 2)
  YELLOW=$(tput setaf 3)
  RED=$(tput setaf 1)
else
  BOLD=""
  DIM=""
  RESET=""
  BLUE=""
  GREEN=""
  YELLOW=""
  RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say() { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  {
    if command -v wslview >/dev/null 2>&1; then
      wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then
      explorer.exe "$url"
    elif command -v xdg-open >/dev/null 2>&1; then
      xdg-open "$url"
    elif command -v open >/dev/null 2>&1; then
      open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line
  line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" >"$tmp" || true
  printf '%s=%s\n' "$key" "$value" >>"$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  ((${#WRITTEN_ENV[@]})) && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  ((${#WRITTEN_SECRET[@]})) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if ((${#SKIPPED[@]})); then
    printf '\n'
    warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Creates or rotates grafana/capacity-auto-resolver-token: the bearer token that
# Alertmanager (storage-alert-routing webhook) and the resolver
# (ALERTMANAGER_WEBHOOK_TOKEN) share. The value is generated here, piped to
# kubectl on stdin, and never echoed, passed in argv, or written to a file or
# .env. Nothing in CI uses it, so no GitHub secret is set. (IMPR-1156)

TOTAL_STAGES=3

NAMESPACE="grafana"
SECRET_NAME="capacity-auto-resolver-token"
DEPLOYMENT="capacity-auto-resolver"
EXPECTED_CONTEXT="${EXPECTED_CONTEXT:-tailnet}"
RESULT="unchanged"
ROTATED=0

banner "Capacity auto-resolver: webhook token"

# ── Stage 1 ────────────────────────────────────────────────────────────────
stage "Preflight: cluster, tools, current state"
for tool in kubectl openssl base64; do
  command -v "$tool" >/dev/null 2>&1 || {
    warn "$tool is not installed"
    exit 1
  }
done
context=$(kubectl config current-context 2>/dev/null || true)
if [[ "$context" != "$EXPECTED_CONTEXT" ]]; then
  warn "kube context is '${context:-none}', expected '$EXPECTED_CONTEXT' (the homelab)."
  confirm "Continue against '${context:-none}' anyway?" || exit 1
fi
# Pin the context so a context switch mid-run cannot redirect a write.
KUBECTL=(kubectl --context "$context")
"${KUBECTL[@]}" get namespace "$NAMESPACE" >/dev/null || {
  warn "namespace $NAMESPACE is not reachable"
  exit 1
}
secret_exists=0
"${KUBECTL[@]}" -n "$NAMESPACE" get secret "$SECRET_NAME" >/dev/null 2>&1 && secret_exists=1
deployment_exists=0
"${KUBECTL[@]}" -n "$NAMESPACE" get deployment "$DEPLOYMENT" >/dev/null 2>&1 && deployment_exists=1
say "Context:        $context"
say "Secret:         $NAMESPACE/$SECRET_NAME $( ((secret_exists)) && echo 'exists' || echo 'absent')"
say "Resolver pod:   $( ((deployment_exists)) && echo 'deployed' || echo 'not deployed yet')"
note "Consumers: the storage-alert-routing webhook (Bearer credentials) and the"
note "resolver Deployment's ALERTMANAGER_WEBHOOK_TOKEN."
pause

# ── Stage 2 ────────────────────────────────────────────────────────────────
stage "Create or rotate the token"
if ((secret_exists)); then
  say "The Secret already exists. Rotating replaces the token everywhere."
  note "Alertmanager's operator re-reads the Secret on its own. A deployed resolver"
  note "keeps the old token until it restarts (offered in stage 3). Until then its"
  note "webhook calls get 401. Slack delivery is unaffected: it's a separate route."
  if confirm "Rotate $NAMESPACE/$SECRET_NAME now?"; then ROTATED=1; fi
else
  say "A fresh 64-character hex token will be generated with openssl and stored"
  say "as $NAMESPACE/$SECRET_NAME (key: token). It is never displayed."
  confirm "Create the Secret now?" || {
    SKIPPED+=("Secret $NAMESPACE/$SECRET_NAME was not created; re-run this wizard")
    finish
    exit 0
  }
fi
if ((! secret_exists || ROTATED)); then
  token=$(openssl rand -hex 32)
  [[ ${#token} -eq 64 ]] || {
    warn "openssl produced an unexpected token length"
    exit 1
  }
  # printf is a shell builtin: the token reaches kubectl on stdin, not argv.
  # create/replace, never apply: apply would copy the value into the
  # last-applied-configuration annotation.
  if ((secret_exists)); then
    printf '%s' "$token" \
      | "${KUBECTL[@]}" -n "$NAMESPACE" create secret generic "$SECRET_NAME" \
        --from-file=token=/dev/stdin --dry-run=client -o yaml \
      | "${KUBECTL[@]}" replace -f - >/dev/null
    RESULT="rotated"
  else
    printf '%s' "$token" \
      | "${KUBECTL[@]}" -n "$NAMESPACE" create secret generic "$SECRET_NAME" \
        --from-file=token=/dev/stdin >/dev/null
    RESULT="created"
  fi
  unset token
  "${KUBECTL[@]}" -n "$NAMESPACE" label secret "$SECRET_NAME" --overwrite \
    app.kubernetes.io/name=capacity-auto-resolver >/dev/null
  "${KUBECTL[@]}" -n "$NAMESPACE" annotate secret "$SECRET_NAME" --overwrite \
    "capacity-resolver.homelab/token-set-at=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >/dev/null
  printf '  %s✓ %s%s %s/%s\n' "$GREEN" "$RESULT" "$RESET" "$NAMESPACE" "$SECRET_NAME"
else
  say "Keeping the existing token."
fi
pause

# ── Stage 3 ────────────────────────────────────────────────────────────────
stage "Verify"
# Only the length and shape are checked; the value never reaches the screen.
stored_len=$("${KUBECTL[@]}" -n "$NAMESPACE" get secret "$SECRET_NAME" \
  -o jsonpath='{.data.token}' | base64 -d | wc -c | tr -d ' ')
if [[ "$stored_len" -ge 32 ]]; then
  printf '  %s✓ key token present%s (%s characters; the resolver requires 32 or more)\n' \
    "$GREEN" "$RESET" "$stored_len"
else
  warn "key token is missing or shorter than 32 characters ($stored_len)"
  SKIPPED+=("Fix $NAMESPACE/$SECRET_NAME: key token must be 32+ characters")
fi
if ((ROTATED && deployment_exists)); then
  say "The deployed resolver still holds the old token."
  if confirm "Restart deployment/$DEPLOYMENT now?"; then
    "${KUBECTL[@]}" -n "$NAMESPACE" rollout restart "deployment/$DEPLOYMENT" >/dev/null
    "${KUBECTL[@]}" -n "$NAMESPACE" rollout status "deployment/$DEPLOYMENT" --timeout=120s
  else
    SKIPPED+=("kubectl -n $NAMESPACE rollout restart deployment/$DEPLOYMENT")
  fi
fi
if ((! deployment_exists)); then
  SKIPPED+=("Once homelab#158 is merged: run longhorn/deploy-storage-alerts.sh from main (resolver in dry-run, then the route)")
fi
pause

finish
note "Secret $NAMESPACE/$SECRET_NAME: $RESULT"
printf '\n'
