#!/usr/bin/env -S uv run --with botocore python3
"""
Consolidate the `homelab` R2 bucket's `media/` subtree.

Actions (per the plan generated by this script itself — re-generated on every run):
  - RENAME: `Kasey's Playlists/*` -> `YouTube/Kasey's Playlists/*`
  - DELETE: lowercase `Youtube/*` (case-duplicates of `YouTube/*`) — frees ~48 GB
  - DELETE: `runs/` (drop)
  - KEEP: existing `YouTube/<category>/` trees (Essential, Nice, Study, Wow, Ugh, Gotta...)

Safety:
  - Default mode is DRY-RUN (prints the plan, makes zero writes).
  - Pass --apply to actually mutate.
  - No backup is written. The source data is backed by a Longhorn volume snapshot.
  - Renames are copy-then-delete (server-side copy, no payload transfer).
  - Mutations run in parallel via threads; tune --concurrency to throttle R2 QPS.

Usage:
    # dry-run (default)
    uv run media/yt-dlp/scripts/r2-consolidate.py

    # apply
    uv run media/yt-dlp/scripts/r2-consolidate.py --apply

    # apply with custom parallelism (default 8)
    uv run media/yt-dlp/scripts/r2-consolidate.py --apply --concurrency 16
"""
import argparse
import concurrent.futures
import datetime
import hashlib
import hmac
import json
import os
import sys
import threading
import time
import urllib.error
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET
from collections import defaultdict

AK = os.environ.get("R2_AK", "252fd0b63874b32278a38ae39cff877b")
SK = os.environ.get("R2_SK", "4999254a6b3cb663b35238b256a9f39153cb44501832f3c03378c2ef7ddfeeea")
ACCOUNT_ID = os.environ.get("R2_ACCOUNT_ID", "e9f17cd063113cea9c2e73c302971066")
BUCKET = os.environ.get("R2_BUCKET", "homelab")
HOST = f"{ACCOUNT_ID}.r2.cloudflarestorage.com"
NS = {"s3": "http://s3.amazonaws.com/doc/2006-03-01/"}

OLD_BASE = "backups/cluster/homelab-k3s/volumes/archive/media/"
NEW_BASE = OLD_BASE + "YouTube/"


# ---------- SigV4 signer (UNSIGNED-PAYLOAD, TLS 1.3) ----------

def sigv4(canonical_query: str) -> tuple[str, str]:
    now = datetime.datetime.now(datetime.timezone.utc)
    amz_date = now.strftime("%Y%m%dT%H%M%SZ")
    date_stamp = amz_date[:8]
    canonical_uri = f"/{BUCKET}"
    canonical_headers = (
        f"host:{HOST}\n"
        f"x-amz-content-sha256:UNSIGNED-PAYLOAD\n"
        f"x-amz-date:{amz_date}\n"
    )
    canonical_request = "\n".join(
        [
            "GET",
            canonical_uri,
            canonical_query,
            canonical_headers,
            "host;x-amz-content-sha256;x-amz-date",
            "UNSIGNED-PAYLOAD",
        ]
    )
    scope = f"{date_stamp}/auto/s3/aws4_request"
    string_to_sign = "\n".join(
        [
            "AWS4-HMAC-SHA256",
            amz_date,
            scope,
            hashlib.sha256(canonical_request.encode()).hexdigest(),
        ]
    )

    def h(k, d):
        return hmac.new(k, d.encode("utf-8"), hashlib.sha256).digest()

    k_date = h(("AWS4" + SK).encode(), date_stamp)
    k_region = h(k_date, "auto")
    k_service = h(k_region, "s3")
    k_signing = h(k_service, "aws4_request")
    sig = hmac.new(k_signing, string_to_sign.encode(), hashlib.sha256).hexdigest()
    return (
        f"AWS4-HMAC-SHA256 Credential={AK}/{scope}, "
        f"SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature={sig}",
        amz_date,
    )


def canonical_query_string(params: dict[str, str]) -> str:
    """Build the canonical query string.

    S3 SigV4 requires %20 (not '+') for spaces in canonical query strings.
    `urllib.parse.urlencode` defaults to `quote_plus` which is wrong here.
    """
    return "&".join(
        f"{k}={urllib.parse.quote(v, safe='')}" for k, v in sorted(params.items())
    )


def sigv4_for_method(method: str, canonical_uri: str, canonical_query: str) -> tuple[str, str]:
    """Sign a request where the body is UNSIGNED-PAYLOAD.

    PUT/POST/DELETE use the same canonical structure as GET; we share this helper.
    """
    now = datetime.datetime.now(datetime.timezone.utc)
    amz_date = now.strftime("%Y%m%dT%H%M%SZ")
    date_stamp = amz_date[:8]
    canonical_headers = (
        f"host:{HOST}\n"
        f"x-amz-content-sha256:UNSIGNED-PAYLOAD\n"
        f"x-amz-date:{amz_date}\n"
    )
    canonical_request = "\n".join(
        [
            method,
            canonical_uri,
            canonical_query,
            canonical_headers,
            "host;x-amz-content-sha256;x-amz-date",
            "UNSIGNED-PAYLOAD",
        ]
    )
    scope = f"{date_stamp}/auto/s3/aws4_request"
    string_to_sign = "\n".join(
        [
            "AWS4-HMAC-SHA256",
            amz_date,
            scope,
            hashlib.sha256(canonical_request.encode()).hexdigest(),
        ]
    )

    def h(k, d):
        return hmac.new(k, d.encode("utf-8"), hashlib.sha256).digest()

    k_date = h(("AWS4" + SK).encode(), date_stamp)
    k_region = h(k_date, "auto")
    k_service = h(k_region, "s3")
    k_signing = h(k_service, "aws4_request")
    sig = hmac.new(k_signing, string_to_sign.encode(), hashlib.sha256).hexdigest()
    return (
        f"AWS4-HMAC-SHA256 Credential={AK}/{scope}, "
        f"SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature={sig}",
        amz_date,
    )


# ---------- request helpers ----------

# Global rate limiter: at most N requests per second across all threads.
# R2's SigV4 signing timestamp has 1-second resolution, so back-to-back
# requests can collide. We pace them out, but allow parallelism.
_RPS = 32  # ~32 req/s aggregate; safe headroom under R2's per-key limits
_TOKEN_LOCK = threading.Lock()
_TOKENS = _RPS
_LAST = time.monotonic()


def _take_token():
    global _TOKENS, _LAST
    while True:
        with _TOKEN_LOCK:
            now = time.monotonic()
            elapsed = now - _LAST
            _TOKENS = min(_RPS, _TOKENS + elapsed * _RPS)
            _LAST = now
            if _TOKENS >= 1:
                _TOKENS -= 1
                return
        # No token; sleep briefly and retry.
        time.sleep(1.0 / _RPS)


def request(method: str, key: str, params: dict[str, str] | None = None):
    """Issue a signed R2 request. `key` is the object key (not URL-encoded)."""
    _take_token()
    params = params or {}
    canonical_query = canonical_query_string(params)
    canonical_uri = "/" + urllib.parse.quote(BUCKET, safe="") + "/" + urllib.parse.quote(key, safe="")
    auth, amz_date = sigv4_for_method(method, canonical_uri, canonical_query)
    url = f"https://{HOST}{canonical_uri}"
    if canonical_query:
        url += "?" + canonical_query
    req = urllib.request.Request(
        url,
        headers={
            "Authorization": auth,
            "x-amz-date": amz_date,
            "x-amz-content-sha256": "UNSIGNED-PAYLOAD",
            "Host": HOST,
        },
        method=method,
    )
    return urllib.request.urlopen(req)


def list_v2(prefix: str, with_delim: bool = False, continuation_token: str | None = None):
    params: dict[str, str] = {"list-type": "2", "max-keys": "1000"}
    if with_delim:
        params["delimiter"] = "/"
    if prefix:
        params["prefix"] = prefix
    if continuation_token:
        params["continuation-token"] = continuation_token
    with request("GET", "", params) as r:
        return ET.fromstring(r.read().decode())


def drain_keys(prefix: str) -> list[tuple[str, int]]:
    """Paged to completion. Returns list of (key, size)."""
    out: list[tuple[str, int]] = []
    token = None
    while True:
        root = list_v2(prefix, with_delim=False, continuation_token=token)
        for c in root.findall("s3:Contents", NS):
            out.append(
                (
                    c.find("s3:Key", NS).text,
                    int(c.find("s3:Size", NS).text),
                )
            )
        if root.get("IsTruncated") == "true":
            token = root.get("NextContinuationToken")
        else:
            return out


# ---------- mutation helpers ----------

def copy_object(src_key: str, dst_key: str) -> int:
    """Server-side copy. Returns the HTTP status code."""
    _take_token()
    # The copy source is sent in the x-amz-copy-source header (URL-encoded key).
    # The destination key is part of the request URL.
    params: dict[str, str] = {}
    canonical_query = canonical_query_string(params)
    canonical_uri = "/" + urllib.parse.quote(BUCKET, safe="") + "/" + urllib.parse.quote(dst_key, safe="")
    auth, amz_date = sigv4_for_method("PUT", canonical_uri, canonical_query)
    url = f"https://{HOST}{canonical_uri}"
    if canonical_query:
        url += "?" + canonical_query
    copy_source = f"/{BUCKET}/{urllib.parse.quote(src_key, safe='')}"
    req = urllib.request.Request(
        url,
        headers={
            "Authorization": auth,
            "x-amz-date": amz_date,
            "x-amz-content-sha256": "UNSIGNED-PAYLOAD",
            "Host": HOST,
            "x-amz-copy-source": copy_source,
        },
        method="PUT",
    )
    with urllib.request.urlopen(req) as r:
        return r.status


def delete_object(key: str) -> int:
    _take_token()
    params: dict[str, str] = {}
    canonical_query = canonical_query_string(params)
    canonical_uri = "/" + urllib.parse.quote(BUCKET, safe="") + "/" + urllib.parse.quote(key, safe="")
    auth, amz_date = sigv4_for_method("DELETE", canonical_uri, canonical_query)
    url = f"https://{HOST}{canonical_uri}"
    if canonical_query:
        url += "?" + canonical_query
    req = urllib.request.Request(
        url,
        headers={
            "Authorization": auth,
            "x-amz-date": amz_date,
            "x-amz-content-sha256": "UNSIGNED-PAYLOAD",
            "Host": HOST,
        },
        method="DELETE",
    )
    with urllib.request.urlopen(req) as r:
        return r.status


def head_object(key: str) -> int:
    """HEAD probe. Returns the HTTP status code (200 = exists, 404 = absent)."""
    _take_token()
    params: dict[str, str] = {}
    canonical_query = canonical_query_string(params)
    canonical_uri = "/" + urllib.parse.quote(BUCKET, safe="") + "/" + urllib.parse.quote(key, safe="")
    auth, amz_date = sigv4_for_method("HEAD", canonical_uri, canonical_query)
    url = f"https://{HOST}{canonical_uri}"
    if canonical_query:
        url += "?" + canonical_query
    req = urllib.request.Request(
        url,
        headers={
            "Authorization": auth,
            "x-amz-date": amz_date,
            "x-amz-content-sha256": "UNSIGNED-PAYLOAD",
            "Host": HOST,
        },
        method="HEAD",
    )
    try:
        with urllib.request.urlopen(req) as r:
            return r.status
    except urllib.error.HTTPError as e:
        return e.code


# ---------- plan ----------

# (source_prefix, target_relative_under_NEW_BASE | None, action)
SOURCES = [
    (OLD_BASE + "YouTube/Essential/",                  "Essential/", "KEEP"),
    (OLD_BASE + "YouTube/Gotta Keep These Somewhere/", "Gotta Keep These Somewhere/", "KEEP"),
    (OLD_BASE + "YouTube/Nice/",                       "Nice/", "KEEP"),
    (OLD_BASE + "YouTube/Study/",                      "Study/", "KEEP"),
    (OLD_BASE + "YouTube/Ugh/",                        "Ugh/", "KEEP"),
    (OLD_BASE + "YouTube/Wow/",                        "Wow/", "KEEP"),
    (OLD_BASE + "Kasey's Playlists/",                  "Kasey's Playlists/", "RENAME"),
    (OLD_BASE + "Youtube/Essential/",                  None, "DELETE"),
    (OLD_BASE + "Youtube/Gotta Keep These Somewhere/", None, "DELETE"),
    (OLD_BASE + "Youtube/Nice/",                       None, "DELETE"),
    (OLD_BASE + "Youtube/Study/",                      None, "DELETE"),
    (OLD_BASE + "runs/",                               None, "DELETE"),
]


def build_plan() -> list[dict]:
    plan: list[dict] = []
    for source, target_rel, action in SOURCES:
        for key, size in drain_keys(source):
            if action == "KEEP":
                plan.append({"action": "KEEP", "src": key, "dst": key, "size": size})
            elif action == "RENAME":
                dst = NEW_BASE + target_rel + key[len(source):]
                plan.append({"action": "RENAME", "src": key, "dst": dst, "size": size})
            elif action == "DELETE":
                plan.append({"action": "DELETE", "src": key, "dst": None, "size": size})
    return plan


def print_plan(plan: list[dict]) -> None:
    by_action: dict[str, list[dict]] = defaultdict(list)
    for p in plan:
        by_action[p["action"]].append(p)
    print("=" * 80)
    print("R2 MEDIA CONSOLIDATION PLAN")
    print("=" * 80)
    for action in ("KEEP", "RENAME", "DELETE"):
        items = by_action[action]
        if not items:
            continue
        total = sum(p["size"] for p in items)
        print(f"\n{action}: {len(items)} objects, {total/1e9:.3f} GB")
        for p in items[:3]:
            if p["action"] == "DELETE":
                print(f"  {p['src']}  ({p['size']/1e6:.1f} MB)")
            else:
                print(f"  {p['src']}\n    -> {p['dst']}")
        if len(items) > 3:
            print(f"  ... and {len(items) - 3} more")
    print()


def apply_plan(plan: list[dict], concurrency: int) -> None:
    """Two-phase: RENAME first (copy + delete-source), DELETE second.

    For each RENAME, we copy the source to the destination, then delete the source.
    This is not transactional — if any step fails, we stop and surface the error.
    Mutations are parallelised across `concurrency` threads.
    """
    renames = [p for p in plan if p["action"] == "RENAME"]
    deletes = [p for p in plan if p["action"] == "DELETE"]

    rename_lock = threading.Lock()
    rename_done = [0]

    def do_rename(p: dict):
        # Server-side copy (no payload transfer) to the destination.
        status = copy_object(p["src"], p["dst"])
        if status != 200:
            raise RuntimeError(f"copy failed: {p['src']} -> {p['dst']} (HTTP {status})")
        # Then delete the source.
        status = delete_object(p["src"])
        if status not in (202, 204):
            raise RuntimeError(f"delete-after-copy failed: {p['src']} (HTTP {status})")
        with rename_lock:
            rename_done[0] += 1
            done = rename_done[0]
        if done % 100 == 0 or done == len(renames):
            print(f"  [rename {done}/{len(renames)}]", flush=True)

    print(f"Phase 1: RENAME  ({len(renames)} objects, concurrency={concurrency})")
    run_parallel(do_rename, renames, concurrency)

    delete_lock = threading.Lock()
    delete_done = [0]

    def do_delete(p: dict):
        status = delete_object(p["src"])
        if status not in (202, 204):
            raise RuntimeError(f"delete failed: {p['src']} (HTTP {status})")
        with delete_lock:
            delete_done[0] += 1
            done = delete_done[0]
        if done % 100 == 0 or done == len(deletes):
            print(f"  [delete {done}/{len(deletes)}]", flush=True)

    print(f"\nPhase 2: DELETE  ({len(deletes)} objects, concurrency={concurrency})")
    run_parallel(do_delete, deletes, concurrency)

    print("\nAll operations succeeded.")


def run_parallel(fn, items, concurrency):
    """Run `fn(item)` over `items` in parallel; raise on first exception."""
    if not items:
        return
    with concurrent.futures.ThreadPoolExecutor(max_workers=concurrency) as ex:
        futs = [ex.submit(fn, p) for p in items]
        # as_completed yields in completion order; surface the first failure.
        for fut in concurrent.futures.as_completed(futs):
            exc = fut.exception()
            if exc is not None:
                # Best-effort cancel siblings; they're either pending or running.
                for f in futs:
                    f.cancel()
                raise exc


def verify_post_state() -> None:
    """Spot-check the post-state: each target prefix should still resolve."""
    print("\nPost-state verification:")
    for source, target_rel, action in SOURCES:
        if action == "KEEP":
            keys = drain_keys(source)
            print(f"  KEEP   {source}  ->  {len(keys)} objects")
        elif action == "RENAME":
            dst_prefix = NEW_BASE + target_rel
            keys = drain_keys(dst_prefix)
            print(f"  RENAMED -> {dst_prefix}  ->  {len(keys)} objects")
            # Source prefix should now be empty.
            leftover = drain_keys(source)
            if leftover:
                print(f"  WARNING: source still has {len(leftover)} objects: {source}")
        elif action == "DELETE":
            leftover = drain_keys(source)
            if leftover:
                print(f"  DELETE {source}  ->  STILL HAS {len(leftover)} objects!  (FAIL)")
            else:
                print(f"  DELETE {source}  ->  empty  (OK)")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true", help="Actually mutate. Default is dry-run.")
    ap.add_argument(
        "--concurrency",
        type=int,
        default=8,
        help="Worker threads for mutations (default 8). 16-32 is fine for R2; >32 risks 429s.",
    )
    args = ap.parse_args()

    print("Building plan (re-enumerating all source prefixes)...")
    plan = build_plan()
    print_plan(plan)

    if not args.apply:
        print("DRY-RUN. Pass --apply to execute.")
        sys.exit(0)

    print("=" * 80)
    print("APPLYING PLAN")
    print("=" * 80)
    apply_plan(plan, concurrency=args.concurrency)
    verify_post_state()


if __name__ == "__main__":
    main()
