---
apiVersion: v1
kind: Service
metadata:
  name: embedder-llamacpp
  namespace: viking
spec:
  type: ClusterIP
  selector:
    app: embedder-llamacpp
  ports:
    - name: http
      port: 8080
      targetPort: 8000
      protocol: TCP
