---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openviking-standalone-config
  namespace: viking
data:
  ov.conf: |
    {
      "default_account": "default",
      "default_user": "noot",
      "storage": {
        "workspace": "/app/data",
        "transaction": {
          "lock_timeout": 30.0,
          "lock_expire": 300.0
        },
        "vectordb": {
          "backend": "local",
          "name": "context",
          "dimension": 768
        },
        "agfs": {
          "backend": "local"
        }
      },
      "code": {
        "code_summary_mode": "ast"
      },
      "rerank": {
        "threshold": 0.2
      },
      "server": {
        "host": "0.0.0.0",
        "port": 1933,
        "workers": 1,
        "root_api_key": "${API_KEY}"
      },
      "log": {
        "level": "INFO",
        "output": "stdout"
      },
      "embedding": {
        "dense": {
          "provider": "openai",
          "model": "nomic-embed-text-v1.5",
          "api_key": "sk-no-key-required",
          "api_base": "http://embedder-llamacpp.viking.svc.cluster.local:8080/v1",
          "dimension": 768,
          "batch_size": 128
        },
        "max_concurrent": 4
      },
      "vlm": {
        "provider": "litellm",
        "model": "openai/current.gguf",
        "api_key": "sk-no-key-required",
        "api_base": "http://llamacpp-rocm-llm.viking.svc.cluster.local/v1",
        "max_concurrent": 2
      }
    }
