---
apiVersion: v1
kind: Service
metadata:
  name: openviking
  namespace: viking
  labels:
    app: openviking
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 1933
      protocol: TCP
      targetPort: 1933
    - name: metrics
      port: 9210
      protocol: TCP
      targetPort: 9210
  selector:
    app: openviking
