apiVersion: v1
kind: Service
metadata:
  name: llamacpp-rocm-llm
  namespace: viking
spec:
  type: ClusterIP
  selector:
    app: llamacpp-rocm
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP