---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-model-cache
  namespace: llama
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: longhorn-ssd
  volumeMode: Filesystem
