---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openviking-config
  namespace: viking
data:
  api-key: "47067ca1b704af555e417d8abf18ceebfa2e54f88e08b7d66db6f457d51fff55"
  ov.conf: |
    {
      "default_account": "default",
      "default_user": "noot",
      "storage": {
        "workspace": "/app/data",
        "vectordb": {
          "backend": "local",
          "name": "context",
          "dimension": 768
        },
        "agfs": {
          "backend": "s3",
          "s3": {
            "bucket": "openviking-agfs",
            "endpoint": "http://garage.garage.svc.cluster.local:3900",
            "region": "garage",
            "access_key": "GKb0157d7a1f22c8e39c5464fc",
            "secret_key": "870141d4a56187469b076fa35840a8b0422313c43df47d8d367879c8bf603866",
            "use_path_style": true
          }
        }
      },
      "code": {
        "code_summary_mode": "ast"
      },
      "rerank": {
        "threshold": 0.2
      },
      "server": {
        "host": "0.0.0.0",
        "port": 1933,
        "workers": 1,
        "root_api_key": "47067ca1b704af555e417d8abf18ceebfa2e54f88e08b7d66db6f457d51fff55"
      },
      "log": {
        "level": "INFO",
        "output": "stdout"
      },
      "embedding": {
        "dense": {
          "provider": "openai",
          "model": "nomic-embed-text-v1.5",
          "api_key": "sk-no-key-required",
          "api_base": "http://embedder-llamacpp.viking.svc.cluster.local:8080/v1",
          "dimension": 768,
          "batch_size": 64
        },
        "max_concurrent": 4
      },
      "vlm": {
        "provider": "litellm",
        "model": "openai/qwen3-8b",
        "api_key": "sk-no-key-required",
        "api_base": "http://llamacpp-rocm-llm.viking.svc.cluster.local/v1",
        "max_concurrent": 10
      }
    }
