version: 5
daemon:
  log_level: info
  admin_group: sudo
  disable_clocks_cleanup: false
apply_settings_timer: 5
current_profile: null
auto_switch_profiles: false
gpus:
  1002:7550-1849:5414-0000:03:00.0:
    fan_control_enabled: true
    fan_control_settings:
      mode: curve
      temperature_key: junction
      interval_ms: 500
      curve:
        40: 0.3
        60: 0.4
        75: 0.6
        82: 0.8
        88: 1.0
      spindown_delay_ms: 5000
