---
apiVersion: v1
kind: Pod
metadata:
  name: rocm-smi-test
  namespace: default
spec:
  restartPolicy: OnFailure
  nodeSelector:
    gpu.vendor: amd
  containers:
    - name: rocm-smi
      image: rocm/rocm-terminal:latest
      command: ["rocm-smi"]
      resources:
        limits:
          amd.com/gpu: 1
      securityContext:
        privileged: true
