---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudflared
  namespace: garage
automountServiceAccountToken: false

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: garage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      serviceAccountName: cloudflared
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: network
                    operator: NotIn
                    values:
                      - wifi
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            - --no-autoupdate
            - run
            - --token-file=/etc/cloudflared/token
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: tokenfile
              mountPath: /etc/cloudflared
              readOnly: true
      volumes:
        - name: tokenfile
          secret:
            secretName: uploads-cloudflared-token
            items:
              - key: TOKEN
                path: token
